project_id = "lrzyznsxeidnzcthknwc"

[functions.generate-emails]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.gmail-auth-url]
verify_jwt = false

[functions.gmail-exchange-token]
verify_jwt = false

[functions.send-gmail-email]
verify_jwt = false

[functions.gmail-check-connection]
verify_jwt = false

[functions.gmail-disconnect]
verify_jwt = false

[functions.gmail-callback]
verify_jwt = false
